resource_group_name = "rg-sandbox"
location           = "East US"
prefix             = "sandbox"
vm_size            = "Standard_B2s"
admin_username     = "azureuser"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
